

train:
  train_images_path: "../../data/processed/train_images.pt"
  train_targets_path: "../../data/processed/train_targets.pt"
  batch_size: 10
  num_epochs: 10
  learning_rate: 0.001

evaluate:
  test_images_path: "../../data/processed/test_images.pt"
  test_targets_path: "../../data/processed/test_targets.pt"
  model_path: "../../models/model.pth"
  batch_size: 10
