program: src/mlops_project/train.py
command:
  - "${env}"
  - "${interpreter}"
  - "src/mlops_project/train.py"
  - "train"

name: hyperparameter_sweep
project: mlops_project
method: grid
metric:
    goal: minimize
    name: train_loss
parameters:
    learning_rate:
        values: [0.01, 0.001, 0.0001]
    batch_size:
        values: [8, 16]
    epochs:
        values: [5, 10]
run_cap: 15
