name: Data Change Workflow

on:
  push:
    paths:
      - "data/**"  # Monitor changes in the "data" folder

jobs:
  data_change:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Step 3: Install required dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the data pipeline script
      - name: Run Data Pipeline
        run: |
          python src/mlops_project/data.py

      # Step 5: (Optional) Generate a data report
      - name: Generate Data Report
        run: |
          python src/mlops_project/visualize.py
