name: Trigger on Model or Training Changes

on:
  push:
    paths:
      - "model/**"          # Monitorea cambios en la carpeta model/
      - "train.py"          # Monitorea cambios en el archivo train.py
      - "evaluate.py"       # Monitorea cambios en evaluate.py
      - "data/**"           # Opcional: monitorea cambios en data/

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python train.py  # Ejecuta el script de entrenamiento

    - name: Evaluate model
      run: |
        python evaluate.py > evaluation_results.txt  # Evalúa el modelo

    - name: Post results to GitHub
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml send-comment --file evaluation_results.txt

