name: Data Change Workflow

on:
  push:
    paths:
      - "data/**"  # Monitor changes in the "data" folder

permissions:
  contents: read

jobs:
  data-change:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Data Pipeline
      run: |
        python src/mlops_project/data.py

   

