name: Trigger on Data Change

on:
  push:
    paths:
      - "data/**"  # Monitorea cambios en la carpeta "data"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python train.py > metrics.txt
        cml send-comment --file metrics.txt
